### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by hevenhm** [Curtis-Jensen/Todo-App#10]
DELIVERABLE

- [ ] Create a TodoList

- [x] Adding items to the List

- [x] Deleting Items to the List

- [ ] Creating the Check Box for the List

- [ ] Checking Items from the List using the Check Box

- [ ] Calendar
